gg.jte.use-precompiled-templates=true
gg.jte.development-mode=false
spring.application.name=rightknight
server.forward-headers-strategy=framework

# DB
spring.datasource.url=jdbc:postgresql://postgresdb:5432/myapp_db
spring.datasource.username=myuser
spring.datasource.password=mypassword

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
