spring.application.name=rightknight

gg.jte.use-precompiled-templates=true
gg.jte.development-mode=false

server.forward-headers-strategy=framework

spring.flyway.enabled=true

stockfish.path=/opt/rightknight/stockfish/stockfish-ubuntu-x86-64-avx2
stockfish.threads=4
stockfish.hash=512
stockfish.defaultdepth=20
stockfish.defaultmulti-pv=5
